{
  'branch_type': 'root',
  'elements': [
    {
      'branch_type': 'bbcode',
      'value': '<!-- s:fight: --><img src="{SMILIES_PATH}/bije.gif" alt=":fight:" title="fight" /><!-- s:fight: -->  <!-- s:hurra: --><img src="{SMILIES_PATH}/hura.gif" alt=":hurra:" title="Hurra!" /><!-- s:hurra: -->  <!-- s:olaboga: --><img src="{SMILIES_PATH}/olaboga.gif" alt=":olaboga:" title="Olaboga" /><!-- s:olaboga: -->  <!-- s:wnerw: --><img src="{SMILIES_PATH}/wnerw.gif" alt=":wnerw:" title="wnerw" /><!-- s:wnerw: --> \n\n <!-- s:fight: --><img src="{SMILIES_PATH}/bije.gif" alt=":fight:" title="fight" /><!-- s:fight: -->  <!-- s:hurra: --><img src="{SMILIES_PATH}/hura.gif" alt=":hurra:" title="Hurra!" /><!-- s:hurra: -->  <!-- s:olaboga: --><img src="{SMILIES_PATH}/olaboga.gif" alt=":olaboga:" title="Olaboga" /><!-- s:olaboga: -->  <!-- s:wnerw: --><img src="{SMILIES_PATH}/wnerw.gif" alt=":wnerw:" title="wnerw" /><!-- s:wnerw: --> \n\n',
      'elements': []
    },
    {
      'branch_type': 'quote',
      'value': '"trekker"',
      'elements': [
        {
          'branch_type': 'bbcode',
          'value': 'bold\n\n[b:17hlnlju]lorem[/b:17hlnlju]\n\nitalic\n\n[i:17hlnlju]lorem[/i:17hlnlju]\n\nunderscore\n\n[u:17hlnlju]lorem[/u:17hlnlju]\n\ncytaty\n',
          'elements': []
        },
        {
          'branch_type': 'quote',
          'value': '',
          'elements': [
            {
              'branch_type': 'bbcode',
              'value': '\njeden\n',
              'elements': []
            },
            {
              'branch_type': 'quote',
              'value': '',
              'elements': [
                {
                  'branch_type': 'bbcode',
                  'value': 'jeden.dwa',
                  'elements': []
                }
              ]
            },
            {
              'branch_type': 'bbcode',
              'value': '\ndwa\n',
              'elements': []
            },
      {'branch_type': 'quote',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'dwa.dwa',
         'elements': []}]},
      {'branch_type': 'bbcode', 'value': '\ntrzy\n', 'elements': []}]},
    {'branch_type': 'quote',
     'value': '',
     'elements': [{'branch_type': 'bbcode',
       'value': 'cztery',
       'elements': []}]},
    {'branch_type': 'bbcode', 'value': '\n\nkod\n\n', 'elements': []},
    {'branch_type': 'code',
     'value': '',
     'elements': [{'branch_type': 'bbcode',
       'value': 'lorem',
       'elements': []}]},
    {'branch_type': 'bbcode', 'value': '\n\nlisty\n\n', 'elements': []},
    {'branch_type': 'list',
     'value': '',
     'elements': [{'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'aaa',
         'elements': []}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'bbb',
         'elements': []}]},
      {'branch_type': 'list',
       'value': '',
       'elements': [{'branch_type': '*',
         'value': '',
         'elements': [{'branch_type': 'bbcode',
           'value': 'aaa',
           'elements': []}]},
        {'branch_type': '*',
         'value': '',
         'elements': [{'branch_type': 'bbcode',
           'value': 'bbb',
           'elements': []}]}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'aaa',
         'elements': []}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'bbb',
         'elements': []}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'aaa',
         'elements': []}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'bbb',
         'elements': []}]}]},
    {'branch_type': 'list',
     'value': '1',
     'elements': [{'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'ccc',
         'elements': []}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'ddd',
         'elements': []}]}]},
    {'branch_type': 'list',
     'value': '1',
     'elements': [{'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'eee',
         'elements': []}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'fff',
         'elements': []}]},
      {'branch_type': 'list',
       'value': 'a',
       'elements': [{'branch_type': '*',
         'value': '',
         'elements': [{'branch_type': 'bbcode',
           'value': '111',
           'elements': []}]},
        {'branch_type': '*',
         'value': '',
         'elements': [{'branch_type': 'bbcode',
           'value': '222',
           'elements': []}]},
        {'branch_type': '*',
         'value': '',
         'elements': [{'branch_type': 'bbcode',
           'value': '333',
           'elements': []}]}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode', 'value': 'x', 'elements': []}]},
      {'branch_type': 'list',
       'value': 'a',
       'elements': [{'branch_type': '*',
         'value': '',
         'elements': [{'branch_type': 'bbcode',
           'value': '111',
           'elements': []}]},
        {'branch_type': 'list',
         'value': 'a',
         'elements': [{'branch_type': '*',
           'value': '',
           'elements': [{'branch_type': 'bbcode',
             'value': '444',
             'elements': []}]},
          {'branch_type': '*',
           'value': '',
           'elements': [{'branch_type': 'bbcode',
             'value': '555',
             'elements': []}]},
          {'branch_type': '*',
           'value': '',
           'elements': [{'branch_type': 'bbcode',
             'value': '666',
             'elements': []}]}]},
        {'branch_type': '*',
         'value': '',
         'elements': [{'branch_type': 'bbcode',
           'value': '333',
           'elements': []}]}]},
      {'branch_type': '*',
       'value': '',
       'elements': [{'branch_type': 'bbcode',
         'value': 'iii',
         'elements': []}]}]},
    {'branch_type': 'bbcode',
     'value': '\n\n[img:17hlnlju]https://v.wpimg.pl/MDc0OC5wYiUCUjlwGgxvMEEKbSpcVWFmFhJ1YRpFfHwbAXxzGgQqMxMeODNWEyNqE1xgIgdHdCZWBXl1DUYvJloELnZTRSl9U1N3IQVDfHRUBHdtRRkqZh4[/img:17hlnlju]\n\n[youtube:17hlnlju]iBxVRwynmmE[/youtube:17hlnlju]\n\n[url:17hlnlju]http://www.wp.pl[/url:17hlnlju]\n\n[url=http://www.wp.pl:17hlnlju]wu pe pe el[/url:17hlnlju]\n\n[s:17hlnlju]strike[/s:17hlnlju]\n\nX[super:17hlnlju]1[/super:17hlnlju]\n\nY[sub:17hlnlju]2[/sub:17hlnlju]\n\n[tex:17hlnlju]asad[/tex:17hlnlju]',
     'elements': []}]}]}